---
- name: revert git
  hosts: webservers
  become: yes

  tasks:
    - name: Install nginx
      yum:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes
